export default {
  'accessor-pairs': 'off',
  'arrow-body-style': ['error', 'as-needed'],
  'block-scoped-var': 'error',
  'camelcase': 'off',
  'capitalized-comments': 'off',
  'class-methods-use-this': 'error',
  'complexity': ['error', 20],
  'consistent-return': 'error',
  'consistent-this': 'error',
  'curly': ['error', 'multi-line', 'consistent'],
  'default-case': 'error',
  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-notation': 'warn',
  'eqeqeq': ['error', 'smart'],
  'func-name-matching': 'error',
  'func-names': ['error', 'as-needed'],
  'func-style': ['error', 'expression'],
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'error',
  'id-denylist': 'off',
  'id-length': 'off',
  'id-match': 'off',
  'init-declarations': 'off',
  'logical-assignment-operators': ['error', 'always'],
  'max-classes-per-file': ['error', 1],
  'max-depth': ['warn', 4],
  'max-lines': 'off',
  'max-lines-per-function': 'off',
  'max-nested-callbacks': ['warn', 3],
  'max-params': ['warn', { max: 3 }],
  'max-statements': ['warn', 10],
  'new-cap': ['error', {
    newIsCap: true,
    capIsNew: true
  }],
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-bitwise': 'warn',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-console': 'warn',
  'no-continue': 'error',
  'no-delete-var': 'error',
  'no-div-regex': 'off',
  'no-else-return': 'error',
  'no-empty': 'error',
  'no-empty-function': 'error',
  'no-empty-static-block': 'error',
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-label': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': ['error', {
    boolean: false,
    number: false,
    string: true,
    disallowTemplateShorthand: false
  }],
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-inline-comments': 'off',
  'no-invalid-this': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'error',
  'no-magic-numbers': 'off',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'off',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-object-constructor': 'error',
  'no-octal': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': 'error',
  'no-plusplus': 'error',
  'no-proto': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-restricted-exports': 'off',
  'no-restricted-globals': 'off',
  'no-restricted-imports': 'off',
  'no-restricted-properties': 'off',
  'no-restricted-syntax': 'off',
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-sequences': 'error',
  'no-shadow': 'error',
  'no-shadow-restricted-names': 'error',
  'no-ternary': 'off',
  'no-throw-literal': 'error',
  'no-undef-init': 'error',
  'no-undefined': 'error',
  'no-underscore-dangle': ['error', {
    allowAfterThis: true
  }],
  'no-unneeded-ternary': 'error',
  'no-unused-expressions': 'error',
  'no-unused-labels': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': 'error',
  'no-warning-comments': 'error',
  'no-with': 'error',
  'object-shorthand': 'error',
  'one-var': ['error', 'never'],
  'operator-assignment': ['error', 'always'],
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-destructuring': ['error', {
    VariableDeclarator: {
      array: false,
      object: true
    },
    AssignmentExpression: {
      array: false,
      object: true
    }
  }],
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'off',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'radix': 'off',
  'require-await': 'error',
  'require-unicode-regexp': 'error',
  'require-yield': 'error',
  'sort-imports': 'off',
  'sort-keys': 'off',
  'sort-vars': 'off',
  'strict': ['error', 'never'],
  'symbol-description': 'error',
  'vars-on-top': 'off',
  'yoda': 'error'
};
